Vagrant.configure("2") do |config|
  config.vm.define "mysql_server" do |mysql_server|
    # BOX CONFIGURATION
    mysql_server.vm.box = "bento/ubuntu-22.04"

    # NETWORKING CONFIGURATION
    mysql_server.vm.network "forwarded_port", guest: 80, host: 8014
    mysql_server.vm.network "private_network", type: "static", ip: "192.168.56.22"

    # PROVIDER CONFIGURATION
    mysql_server.vm.provider "virtualbox" do |vb|
      #  vb.gui = false
      #  vb.memory = "1024"
      #  vb.cpus = 2
    end

    # SYNC FOLDER CONFIGURATION
    mysql_server.vm.synced_folder "./config", "/home/vagrant/config"

    # PROVISIONING CONFIGURATION
    mysql_server.vm.provision "shell", inline: <<-SHELL
      # Install the packages
      sudo apt-get update
      sudo apt-get install -y apt-utils net-tools iputils-ping traceroute nano vim openssh-server ufw
      sudo apt-get install -y mysql-server
    
      # Enable SSH service
      sudo systemctl enable ssh --now
      sudo systemctl start ssh

      # Apply network settings
      sudo ufw allow ssh
      sudo ufw enable
    SHELL
  end
end
